### ISSUE TITLE
Member events not firing

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#24]

**Comment by Simyon264** [comment]
This is a problem with discord! (Source: i had the same issue)
![image](https://user-images.githubusercontent.com/63975668/111020390-ba295900-83c5-11eb-91b4-461bd5755baa.png)
You need to check both tick boxes! If it still doesnt work im going to look into it some more. Oh and i checked the code and it should work.

**Comment by Vylpes** [comment]
That seems to have fixed it! Thanks
